# Generated by Django 5.1.4 on 2025-01-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='nacionalidade',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='sub_titulo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
