# Generated by Django 5.1.4 on 2025-01-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_autores_nacionalidade_alter_livros_sub_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='sub_titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
